language:
  - objective-c
# osx_image: xcode7.3
osx_image: xcode8
env:
  # - DEVICE=9.2
  # - DEVICE=9.3
  - DEVICE=10.0
node_js:
  - "0.12"
install:
  - node --version
  - npm install
  - npm install -g gulp
script:
  - gulp eslint
  - gulp once
  - _FORCE_LOGS=1 gulp e2e-test
after_success:
    - gulp coveralls
